// <!-- REACT IS A JS LIBRARY MADE BY FACEBOOK AND USED BY NETFLIX AND INSTAGRAM -->
// <!-- SINGLE PAGE APPLICATIONS -->
// <!-- REACT IS A LIBRARY NOT A FRAMEWORK -->
// <!-- USES VIRTUAL DOM , NO NEED TO REFRESH DOM -->
// <!-- REACT FIRST CREATES AN EXACT COPY OF THE DOM AND ONLY COPIES THE NEW PART OF VIRTUAL DOM TO ACTUAL DOM  -->
// JSX WILL BE CONVERTED TO JS USING BABEL
// we cant return multiple elements in react at once but we can wrap them in a single element
// WE CAN USE JSX INSIIDE OF LOOPS
// HTML ATTRIBUTES LIKE CLASS BECOME CLASSNAME IN CAMEL CASE
// HTML TAGS MUST ALWAYS BE CLOSED
// 